"""Teks antarmuka (menu, tombol, label) dalam Bahasa Indonesia & Inggris.

Teks konten (profil, visi, misi, dll.) diatur di Airtable, tabel Pengaturan.
"""

T = {
    "id": {
        "lang_nama": "Bahasa Indonesia", "lang_pendek": "ID", "locale": "id_ID",
        "menu": "Menu", "tutup": "Tutup", "lewati": "Langsung ke isi",
        "beranda": "Beranda", "tentang": "Tentang", "program": "Program", "kabar": "Kabar",
        "galeri": "Galeri", "mitra": "Mitra", "dukung": "Dukung Kami", "kontak": "Kontak",
        "ganti_bahasa": "English", "ganti_bahasa_label": "Read in English",
        "tagline_lokasi": "Komunitas di Maumere, Flores",
        "kenali": "Kenali kami", "lihat_semua": "Lihat semua", "selengkapnya": "Selengkapnya",
        "baca": "Baca", "program_kami": "Program & kegiatan", "program_intro": "Advokasi hak dasar, pemberdayaan ekonomi, dan dukungan bagi anggota komunitas di Kabupaten Sikka dan sekitarnya.",
        "kabar_terbaru": "Kabar terbaru", "kabar_intro": "Cerita, catatan kegiatan, dan kabar dari komunitas Fajar Sikka.",
        "galeri_intro": "Dokumentasi kegiatan komunitas. Setiap foto dipublikasikan dengan persetujuan orang-orang di dalamnya.",
        "mitra_intro": "Kerja Fajar Sikka tumbuh bersama lembaga dan komunitas yang berjalan bersama kami.",
        "jejaring": "Jejaring & kerja sama",
        "tentang_kami": "Tentang kami", "latar_belakang": "Latar belakang", "makna_nama": "Arti nama",
        "visi": "Visi", "misi": "Misi", "motto": "Motto", "tujuan": "Tujuan", "sasaran": "Sasaran",
        "makna_logo": "Makna logo", "pengurus": "Susunan pengurus", "penasehat": "Penasehat",
        "ketua_bidang": "Ketua bidang",
        "periode": "Periode", "lokasi": "Lokasi", "bidang": "Bidang", "semua": "Semua",
        "bersama": "Bersama", "program_lain": "Program lainnya", "album_terkait": "Album foto terkait",
        "foto": "foto", "foto_kegiatan": "Foto kegiatan",
        "oleh": "Oleh", "kategori": "Kategori", "bagikan": "Bagikan", "salin_tautan": "Salin tautan",
        "tersalin": "Tautan tersalin", "artikel_lain": "Baca juga", "sebelumnya": "Sebelumnya", "berikutnya": "Berikutnya",
        "halaman": "Halaman", "belum_ada_kabar": "Belum ada kabar yang diterbitkan. Nantikan cerita dari kami segera.",
        "belum_ada_galeri": "Album foto kegiatan akan segera hadir.",
        "hanya_id": "",
        "dukung_judul": "Dukung Fajar Sikka", "dukung_cta": "Berdiri bersama kelompok rentan di Sikka.",
        "donasi_rekening": "Donasi melalui transfer bank", "bank": "Bank", "no_rek": "Nomor rekening", "atas_nama": "Atas nama",
        "salin": "Salin", "donasi_konfirmasi": "Setelah transfer, mohon kabari kami lewat email atau WhatsApp agar donasi Anda dapat kami catat dan laporkan.",
        "donasi_email_judul": "Ingin berdonasi?", "donasi_email": "Informasi rekening donasi dapat diperoleh dengan menghubungi kami langsung. Kami akan membalas secepatnya.",
        "donasi_subjek": "Donasi untuk Fajar Sikka", "kirim_email": "Kirim email", "chat_wa": "Chat WhatsApp",
        "cara_lain": "Cara lain mendukung", "hubungi_kami": "Hubungi kami",
        "kontak_intro": "Kami senang mendengar dari Anda — calon mitra, donor, jurnalis, peneliti, maupun sesama komunitas.",
        "alamat": "Alamat", "telepon": "Telepon", "email": "Email", "media_sosial": "Media sosial",
        "buka_peta": "Buka di Google Maps", "formulir": "Kirim pesan",
        "halaman_tidak_ada": "Halaman tidak ditemukan", "halaman_tidak_ada_teks": "Maaf, halaman yang Anda cari tidak ada atau sudah dipindahkan.",
        "kembali_beranda": "Kembali ke beranda",
        "hak_cipta": "Hak cipta", "foto_lanskap": "Foto lanskap: Flores, Nusa Tenggara Timur.",
        "navigasi": "Navigasi", "berlangganan_rss": "RSS Kabar",
        "sebelum_foto": "Foto sebelumnya", "setelah_foto": "Foto berikutnya", "tutup_foto": "Tutup",
        "berkelanjutan": "Berkelanjutan", "tahun_berdiri": "Berdiri",
    },
    "en": {
        "lang_nama": "English", "lang_pendek": "EN", "locale": "en_US",
        "menu": "Menu", "tutup": "Close", "lewati": "Skip to content",
        "beranda": "Home", "tentang": "About", "program": "Programmes", "kabar": "News",
        "galeri": "Gallery", "mitra": "Partners", "dukung": "Support Us", "kontak": "Contact",
        "ganti_bahasa": "Bahasa Indonesia", "ganti_bahasa_label": "Baca dalam Bahasa Indonesia",
        "tagline_lokasi": "A community in Maumere, Flores",
        "kenali": "Get to know us", "lihat_semua": "See all", "selengkapnya": "Read more",
        "baca": "Read", "program_kami": "Programmes & activities", "program_intro": "Basic-rights advocacy, economic empowerment and care for community members in Sikka Regency and beyond.",
        "kabar_terbaru": "Latest news", "kabar_intro": "Stories, activity notes and news from the Fajar Sikka community.",
        "galeri_intro": "Photos from our community's activities. Every photo is published with the consent of the people in it.",
        "mitra_intro": "Fajar Sikka's work grows alongside the organisations and communities that walk with us.",
        "jejaring": "Networks & partnerships",
        "tentang_kami": "About us", "latar_belakang": "Background", "makna_nama": "Our name",
        "visi": "Vision", "misi": "Mission", "motto": "Motto", "tujuan": "Goals", "sasaran": "Who we serve",
        "makna_logo": "Our logo", "pengurus": "Our team", "penasehat": "Advisors",
        "ketua_bidang": "Division leads",
        "periode": "Period", "lokasi": "Location", "bidang": "Area", "semua": "All",
        "bersama": "With", "program_lain": "Other programmes", "album_terkait": "Related photo albums",
        "foto": "photos", "foto_kegiatan": "Activity photos",
        "oleh": "By", "kategori": "Category", "bagikan": "Share", "salin_tautan": "Copy link",
        "tersalin": "Link copied", "artikel_lain": "Read next", "sebelumnya": "Previous", "berikutnya": "Next",
        "halaman": "Page", "belum_ada_kabar": "No English stories yet. Some of our news is available in Bahasa Indonesia.",
        "belum_ada_galeri": "Photo albums are coming soon.",
        "hanya_id": "Read our news in Bahasa Indonesia",
        "dukung_judul": "Support Fajar Sikka", "dukung_cta": "Stand with vulnerable communities in Sikka.",
        "donasi_rekening": "Donate by bank transfer", "bank": "Bank", "no_rek": "Account number", "atas_nama": "Account name",
        "salin": "Copy", "donasi_konfirmasi": "After transferring, please let us know by email or WhatsApp so we can record and report your gift.",
        "donasi_email_judul": "Would you like to donate?", "donasi_email": "Please contact us directly for our donation account details and for international giving. We'll reply as soon as we can.",
        "donasi_subjek": "Donation to Fajar Sikka", "kirim_email": "Send an email", "chat_wa": "Chat on WhatsApp",
        "cara_lain": "Other ways to help", "hubungi_kami": "Contact us",
        "kontak_intro": "We'd love to hear from you — prospective partners, donors, journalists, researchers and fellow communities alike.",
        "alamat": "Address", "telepon": "Phone", "email": "Email", "media_sosial": "Social media",
        "buka_peta": "Open in Google Maps", "formulir": "Send a message",
        "halaman_tidak_ada": "Page not found", "halaman_tidak_ada_teks": "Sorry, the page you're looking for doesn't exist or has moved.",
        "kembali_beranda": "Back to home",
        "hak_cipta": "Copyright", "foto_lanskap": "Landscape photos: Flores, East Nusa Tenggara.",
        "navigasi": "Navigation", "berlangganan_rss": "News RSS",
        "sebelum_foto": "Previous photo", "setelah_foto": "Next photo", "tutup_foto": "Close",
        "berkelanjutan": "Ongoing", "tahun_berdiri": "Founded",
    },
}

BIDANG_EN = {
    "Advokasi & HAM": "Advocacy & Human Rights",
    "Pemberdayaan Ekonomi": "Economic Empowerment",
    "Kesejahteraan & Kesehatan": "Welfare & Health",
    "Pendidikan & Pengembangan Diri": "Education & Personal Development",
    "Tanggap Darurat": "Emergency Response",
    "Media & Publikasi": "Media & Communications",
}

BULAN = {
    "id": ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus",
           "September", "Oktober", "November", "Desember"],
    "en": ["January", "February", "March", "April", "May", "June", "July", "August",
           "September", "October", "November", "December"],
}

# Makna logo (dari profil komunitas)
LOGO = {
    "id": [
        "Hidup dalam keberagaman seperti tenun ikat yang indah.",
        "Maumere sebagai rumah bagi semua orang marginal dan miskin.",
        "Manusia yang beragam yang menempati bumi yang sama, Flores.",
        "Simbol komunitas sebagai Fajar; sebagai sumber kekuatan Tuhan yang memberi hidup.",
        "Bunga sebagai simbol pertumbuhan, perkembangan, dan keindahan.",
        "Simbol solidaritas dan bumi sebagai tempat manusia hidup, bertumbuh, serta bekerja.",
    ],
    "en": [
        "Living in diversity, like a beautiful ikat weaving.",
        "Maumere as a home for all marginalised and poor people.",
        "Diverse people sharing the same land: Flores.",
        "The community as Fajar — the dawn; a source of God's life-giving strength.",
        "The flower, a symbol of growth, flourishing and beauty.",
        "Solidarity, and the earth as the place where people live, grow and work.",
    ],
}

# Foto lanskap bawaan (dari dokumen profil)
LANSKAP = {
    "padar": ("padar-perbukitan-teluk.jpg",
              {"id": "Perbukitan keemasan dan teluk biru di Nusa Tenggara Timur",
               "en": "Golden hills and blue bays in East Nusa Tenggara"}),
    "pantai": ("pantai-pesisir-flores.jpg",
               {"id": "Pantai berpasir putih dan batu karang di pesisir Flores",
                "en": "White-sand beach and rocky outcrop on the coast of Flores"}),
    "bukit": ("bukit-dan-teluk-flores.jpg",
              {"id": "Bukit hijau menghadap teluk di Flores",
               "en": "Green hills overlooking a bay in Flores"}),
    "airterjun": ("air-terjun-flores.jpg",
                  {"id": "Air terjun bertingkat di tengah hutan Flores",
                   "en": "Terraced waterfall in the forests of Flores"}),
    "senja": ("bukit-senja-flores.jpg",
              {"id": "Bukit hijau dan langit senja di Flores",
               "en": "Green hills under an evening sky in Flores"}),
    # Banner lebar (hero halaman) — potongan resolusi tinggi dari foto lanskap
    "b_program": ("banner-program-perbukitan.jpg",
                  {"id": "Perbukitan dan teluk di Nusa Tenggara Timur", "en": "Hills and bays in East Nusa Tenggara"}),
    "b_kabar": ("banner-kabar-pantai.jpg",
                {"id": "Pantai berpasir putih dan batu karang di pesisir Flores", "en": "White-sand beach and rocky outcrop on the coast of Flores"}),
    "b_galeri": ("banner-galeri-teluk.jpg",
                 {"id": "Lembah keemasan dan teluk melengkung di Nusa Tenggara Timur", "en": "Golden valley and curving bay in East Nusa Tenggara"}),
    "b_kontak": ("banner-kontak-karang.jpg",
                 {"id": "Batu karang dan laut biru di pesisir Flores", "en": "Rocky outcrop and blue sea on the coast of Flores"}),
    "b_dukung": ("banner-dukung-lembah.jpg",
                 {"id": "Perbukitan keemasan di Nusa Tenggara Timur", "en": "Golden hills in East Nusa Tenggara"}),
}
